---
- name: Install apt-transport-https
  apt:
    package=apt-transport-https
    state=installed
    update_cache=true
    
- name: Install ca-certificates
  apt:
    package=ca-certificates
    state=installed
    update_cache=true
    
- name: Add GPG key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

- name: Copying docker.list
  copy:
    src=docker.list
    dest=/etc/apt/sources.list.d/docker.list
    owner=vagrant
    group=root
    mode=0644
    
- name: Update the APT package index
  apt:
    update_cache=true
    
- name: Purge the old repo
  apt:
    package=lxc-docker
    state=absent
    purge=yes
    
- name: Install recommended packages
  action: shell apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
    
- name: Install Docker
  apt:
    package=docker-engine
    state=installed
    update_cache=true
    
- name: Create docker group
  group:
    name=docker
    state=present
    
- name: Add vagrant user to docker group
  user:
    name=vagrant
    group=docker
    append=yes