---
- name: Download Docker Compose
  action: shell curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  
- name: Configure Docker Compose
  action: shell chmod +x /usr/local/bin/docker-compose